name: Integration Test

on:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC

jobs:
  integration-test:
    if: ${{ github.repository == 'benthosdev/benthos' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
        check-latest: true

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Deps
      run: make deps && git diff-index --quiet HEAD || { >&2 echo "Stale go.{mod,sum} detected. This can be fixed with 'make deps'."; exit 1; }

    - name: Integration Test
      run: go test -run "^Test.*Integration$" -timeout 60m ./...
